### ISSUE TITLE
How to build a working 32-bit HTK on 64-bit Linux

### ISSUE THREAD

**Issue by Liontooth** [nassosoassos/sail_align#3]
Hi Nassos,

Thank you for making this available! I ran into the known problem of compiling a working HTK, and found that this works on Debian amd64. Debian stable (wheezy) is still in the middle of a transition to multiarch, but going to a 32-bit bash and forcing -m32 works.

```
htk-3.4.1# linux32 bash
htk-3.4.1# gcc --version
gcc (Debian 4.9.1-16) 4.9.1
```

In configure, add -m32 to force 32-bit compilation:

```
                *linux*)
                                CFLAGS="-m32 -ansi -D_SVID_SOURCE -DOSS_AUDIO -D'ARCH=\"$host_cpu\"' $CFLAGS"
```

Configure with hdecode:

```
./configure --enable-hdecode --enable-trad-htk  --disable-hslab
...
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
```

I issued "make all"; HTK builds without protests:

```
gcc  -m32 -ansi -D_SVID_SOURCE -DOSS_AUDIO -D'ARCH="i686"' -Wall -Wno-switch -g -O2 -I. -DPHNALG   -c -o
```

Verify the executables are 32-bit:

```
# file HVite
HVite: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=0x4ed1a146d336f883329d37392be6debc607f0163, not stripped
```

Then exit the linux32 bash shell to the default 64-bit environment and build sail_align, linking to the 32-bit HTK executables in /usr/local/bin.linux. The test now passes:

```
sail_align-1.4# sail_align -i support/data/timit_5.wav -t support/data/timit_5.txt -w support/test/local -e timit_sample_test -c config/timit_alignment.cfg
Subroutine Audio::Wav::Read::read redefined at /usr/share/perl5/Audio/Wav/Read.pm line 311.
```

Where is the final output? The instructions say "support/data/test/timit_sample_test", which does not exist. I see for instance support/test/local/timit_5.forced.phn, but it doesn't look like the final output. I was imagining something with timestamps next to the words from the task file.

Cheers,
David

**Comment by nassosoassos** [comment]
Hi David,

good to hear that the 32-bit HTK executables have worked. Regarding the
results, these should be in the working directory, specified by the -w
switch at the sail_align call, i.e., in support/test/local.
The confusion is absolutely justified since I haven't updated the README
file accordingly. Apologies for that.

best,
nassos

**Comment by Liontooth** [comment]
Hi Nassos -- 

Thank you! I'm seeing the results, but there's around 500 files in support/test/local. Is there a file that contains just the timestamps and words -- a single summary result file that we would use? I'm sorry if it's obvious.

I'd like to run this on a large dataset, and am concerned at the slow pace. Are there techniques for speeding up the process?

Cheers,
David

**Comment by nassosoassos** [comment]
Hi David,

results are in the .lab file, or .forced.wrd and forced.phn files. The
former corresponds to the iterative process while the latter are the
results of conventional forced alignment (either at the word or at the
phoneme level) on segments identified by the iterative process (check the
doc folder for more details on the algorithm and configuration options). In
challenging cases, the .lab file results are expected to be more reliable.
There are the .1-5.lab files as well containing results of the intermediate
iterations.

For speeding up, there are two main bottlenecks at the moment:
1) Adaptation of the acoustic models to the already aligned segments. This
is currently done on contiguous segments despite their size. For large
segments it may be too slow. (This is something I am currently working on
and plan to have a solution in the next few weeks. For the time being,
sailalign tends to be significantly faster on systems with greater RAM
sizes)
2) ASR on multiple small segments. This could be parallelized.

Please let me know in case you run into any other issues.

best,
nassos

**Comment by Liontooth** [comment]
Nassos -

Thanks, that's very helpful. We're very interested in improving the speed, since we have a large dataset to process. Most of these files are one hour long and have an inaccurate transcript. Could you recommend a work flow? We're finding sail_align chokes on large files. We're also interested in keeping the ASR output -- does the ASR process use the existing transcript to disambiguate? We're happy to help out with testing if that is useful for you.

Best,
David
