### ISSUE TITLE
Network must be specified for recognition from audio - Sampling Rate is 16k

### ISSUE THREAD

**Issue by saikrishnar** [nassosoassos/sail_align#5]
Sir,

Can you please suggest on how to deal with the Out of Vocabulary words?

![sailalign_oov](https://cloud.githubusercontent.com/assets/6652883/6511442/ff35d3d8-c392-11e4-81da-c69846c08b2f.png)

**Comment by nassosoassos** [comment]
I'm not sure how I missed this. So, in the configuration file you have the option to specify a complementary dictionary (check the reference field below, you may add a dictionary there, as shown below):
(example from the timit_alignment.cfg)
  language_modeling => {
             dictionary => {
                 tool            => 'htk',
                 bin_dir         => $BIN_DIR,
                 log_file_suffix => 'dlog',
                 reference       => [
                     catfile( $ROOTPATH, 'language', 'cmu_dictionary.dic' ),
                     catfile( $ROOTPATH, 'language', 'timit_dictionary.dic' ),
                     catfile( 'my_path', 'complementary_dictionary.dic' ),
                 ],
                 output_symbols_list =>
...

Pronunciations there should be defined in the same format as in the cmu_dictionary.
